# ----------------------------------------------------------------------------
# 🛠️ Makefile for Otto Projects
# Runs linters, type checks, tests, and installs dependencies
# Compatible with local development and CI
# ----------------------------------------------------------------------------

.PHONY: help
.DEFAULT_GOAL := help

.ONESHELL:
SHELL := /bin/bash
.SHELLFLAGS := -exc

# Directories for linting and formatting (includes tests)
LINT_DIRS := src/ scripts/ tests/
# Directories for type checking (excludes tests)
TYPECHECK_DIRS := src/ scripts/

help: ## ⁉️  Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | \
	awk 'BEGIN { FS = ":.*?## " }; { printf "\033[36m%-20s\033[0m %s\n", $$1, $$2 }'

install: ## 📦  Create venv & install dependencies
	uv venv
	aws sso login --profile aeprod
	uv sync --all-packages
	uv run pre-commit install
	uv pip install -e .

lock: ## 🔒  Lock dependencies and export requirements.txt files
	uv venv
	uv run uv lock
	echo "# AUTOGENERATED - DO NOT EDIT" > requirements.txt
	uv export --no-dev --no-hashes --format requirements-txt >> requirements.txt
	echo "# AUTOGENERATED - DO NOT EDIT" > dev-requirements.txt
	uv export --only-dev --no-hashes --format requirements-txt >> dev-requirements.txt

lint: ## 🔍  Run Ruff linter
	uv run ruff check $(LINT_DIRS) --fix

format: ## 🧹  Format code with Black
	uv run black $(LINT_DIRS)

typecheck: ## 🔎  Run mypy type checks
	uv run mypy $(TYPECHECK_DIRS)

test: ## 🧪  Run tests with coverage
	uv run pytest -v -l --cov=src tests/ 2>&1

coverage: ## 📊  Show test coverage reports
	uv run coverage report -m
	uv run coverage html
	uv run coverage lcov

check: ## ✅  Run pre-commit on modified files
	uv run pre-commit run --files $(shell git ls-files --modified --others --exclude-standard)

run: ## 🚀  Run the Agent
	uv run python src/task.py
